name: Module CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    uses: xrobot-org/XRobot/.github/workflows/module-ci.yml@v1
    with:
      template-args: '[]'
      image: 'ghcr.io/xrobot-org/docker-image-webots:main'
      apt-packages: 'libopencv-dev libeigen3-dev'
      cmake-options: '-DOpenVINO_DIR=/opt/intel/openvino_2025.4.0/runtime/cmake -DCMAKE_REQUIRE_FIND_PACKAGE_OpenVINO=ON'
      ctest-regex: '^armor_detector_'
  build-without-inference-sdks:
    uses: xrobot-org/XRobot/.github/workflows/module-ci.yml@v1
    with:
      template-args: '[]'
      apt-packages: 'libopencv-dev libeigen3-dev'
      cmake-options: '-DCMAKE_DISABLE_FIND_PACKAGE_OpenVINO=ON -DCMAKE_DISABLE_FIND_PACKAGE_HailoRT=ON'
      ctest-regex: '^armor_detector_'
